language: node_js
node_js:
  - "4"
after_success:
  - npm run coveralls
  - curl --data build=true -X POST https://registry.hub.docker.com/u/telemark/tilskudd.t-fk.no/trigger/c94f0108-78a3-449b-ac4d-057f041a0987/
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8